#!/bin/bash
copy(){
gclone copy goog:{$link} goog:$1 --drive-server-side-across-configs -v 1>&1 | tail -n 5
}
check(){
gclone check goog:{$link} goog:$1 --disable ListR
}
gclone lsd goog: | awk '{print "       ", NR,"         ",$5}'
read -p '''输入连接和保存位置，用空格分开
>>>''' link folder op
link=${link#*id=};link=${link#*folders/};link=${link#*d/};link=${link%?usp*}
foname=$(gclone lsd goog:{$link} --dump bodies -vv 2>&1 | awk 'BEGIN{FS="\""}/^{"id/{print $8}')
fname=$(gclone lsd goog:{$link} --dump bodies -vv 2>&1 | awk 'BEGIN{FS="\""}/^{"id/{print $4}')
[ -z "$foname" ] || [ $link != $fname ] && echo "无效连接" && exit
echo "资源名:  $foname"
case $folder in
	[1-9])
		name=`gclone lsd goog: | awk -v var=$folder 'NR==var {print$5}'`
		echo "保存位置:    $name/$foname/$op"
		copy $name/$foname/$op
		check $name/$foname/$op
		;;
	[1-9][0-9])
		name=`gclone lsd goog: | awk -v var=$folder 'NR==var {print$5}'`
		echo "保存位置:    $name/$foname/$op"
		copy $name/$foname/$op
		check $name/$foname/$op
		;;

	*)
	echo "保存位置:    $folder/$foname"
	copy $folder/$foname
	check $golder/$foname
esac
